### PR TITLE
fix: cosmetic updates on the disclaimer page

### PR DESCRIPTION
**Pull request by Utkarshbhimte**
* added disclaimer to the navbar
* added some styles on the disclaimer page
* removed the coming soon tabs from the navbar

### CODE REVIEW

**Comment by Utkarshbhimte** [comment]
resolved #21

**Comment by Utkarshbhimte** [comment]
@rgxai @SwarnimWalavalkar Can you share the screenshot of why it is failing?

**Comment by nilshah98** [comment]
Hi @Utkarshbhimte for some reason I am not able to view `Disclaimer` in the Navbar in the site that you have hosted.
I can see it in the code, that you are returning it in the `Navbar.jsx` but I am unable to see it there.

Also, as for the vercel deployment, it mentions that checks failed due to authorization error. I will check whether I can fix that and get back to you.

Lastly is it possible to beautify the page a little more?
On my 15 inch laptop, I am getting a horizontal scroll when I go to the `disclaimer` route, and horizontal scrolls aren't so pretty usually.

**Comment by Utkarshbhimte** [comment]
@nilshah98 I have updated the link, check now.

I have fixed the disclaimer liink. There is no horizontal scroll on my testing.

**Pull request merged**
